# Generated by Django 6.0.5 on 2026-06-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comment'),
        ('tickets', '0002_ticket_created_by'),
    ]

    operations = [
    ]
